name: Atualizar ultimo.json automaticamente

on:
  push:
    paths:
      - "historico/*.csv"

permissions:
  contents: write

jobs:
  atualizar-ultimo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar reposit√≥rio
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script gerar_ultimo.py
        run: python gerar_ultimo.py

      - name: Commit e push do ultimo.json e historico.json atualizados
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add historico/ultimo.json
          git add historico/historico.json
          git commit -m "Atualizado automaticamente pelo GitHub Actions" || echo "Nada para commitar"
          git push
